"""Adds model classes

Revision ID: 185483ca362d
Revises: 
Create Date: 2024-03-07 13:36:57.481519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185483ca362d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scooter_id', sa.Integer(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scooter_id'], ['scooter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental')
    op.drop_table('user')
    op.drop_table('scooter')
    # ### end Alembic commands ###
